version: '3.7'
services:
  php8-sf6:
    container_name: php8-sf6
    build: ./docker
    depends_on:
      - database
    ports:
      - "9001:8000"
    volumes:
      - /home/${KAMARADE}/cat-adoption:/var/www/html
  database:
    container_name: db-cat-adoption
    image: postgres:15
    environment:
      POSTGRES_DB: cat-adoption
      # You should definitely change the password in production
      POSTGRES_PASSWORD: admin
      #POSTGRES_USER: admin
    ports:
      - "5666:5432"
  pgadmin:
    container_name: data-admin
    image: adminer
    restart: always
    ports:
      - 5051:8080
